### ISSUE TITLE
Crash on Ensure Submission

### ISSUE THREAD

**Issue by evanlinjin** [skycoin/bbs#183]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x828f49]

goroutine 184 [running]:
github.com/skycoin/bbs/src/store/state.(*BoardInstance).EditBoard.func1(0xc4202edaa0, 0xc4202ff8c0, 0xc420238a58, 0x1)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/state/board_instance_add.go:252 +0x39
github.com/skycoin/bbs/src/store/state.(*BoardInstance).EditPack(0xc420238a50, 0xc420558ca0, 0x0, 0x0)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/state/board_instance.go:313 +0xc2
github.com/skycoin/bbs/src/store/state.(*BoardInstance).EditBoard(0xc420238a50, 0xc420558c80, 0x2, 0x2, 0xc420207510)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/state/board_instance_add.go:249 +0x93
github.com/skycoin/bbs/src/store/state.(*BoardInstance).EnsureSubmissionKeys(0xc420238a50, 0x0, 0x0, 0x0, 0x69a39f8c6d7e663f, 0xc4202335a7, 0xc420238a50)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/state/board_instance_add.go:221 +0x143
github.com/skycoin/bbs/src/store/state.(*Compiler).EnsureSubmissionKeys.func1(0x48a31a620a635a03, 0x2d98388428cb873f, 0x296fed024352a87b, 0x69a39f8c6d7e663f, 0xc375acce49eb69a7, 0x3057f2ec953399e0, 0x5a931a09f8998457, 0xdd1571ef9f2f4559, 0x756ea11a92c14d)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/state/compiler.go:144 +0x107
github.com/skycoin/bbs/src/store/object.(*CXOFileManager).RangeMasterSubs.func1(0x0, 0x904240, 0xc4203c7740, 0x8e55a0, 0xc4203b2a50, 0x0, 0x91fbe0, 0xc420012e00)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/object/cxo_file_manager.go:175 +0x2e2
github.com/skycoin/bbs/src/misc/typ.(*List).Range(0xc420210660, 0x1, 0xc420046620, 0x91fbe0, 0xc420222101)
        /home/evan/go/src/github.com/skycoin/bbs/src/misc/typ/list.go:118 +0xf8
github.com/skycoin/bbs/src/store/object.(*CXOFileManager).RangeMasterSubs(0xc42020c840, 0xc4202fe810, 0x0, 0x0)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/object/cxo_file_manager.go:168 +0xad
github.com/skycoin/bbs/src/store/state.(*Compiler).EnsureSubmissionKeys(0xc4202074f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/evan/go/src/github.com/skycoin/bbs/src/store/state/compiler.go:140 +0x9d
created by github.com/skycoin/bbs/src/store/cxo.(*Manager).relayLoop
        /home/evan/go/src/github.com/skycoin/bbs/src/store/cxo/manager.go:303 +0x2c4
exit status 2

```

**Comment by evanlinjin** [comment]
Sometimes, it happens when quitting the node.

![screenshot from 2017-12-06 01-33-00](https://user-images.githubusercontent.com/14065705/33645096-f65563fc-daad-11e7-8317-1f30d33a0edc.png)
